name: CI

on: 
  push:
    branches:
    - main

jobs:
  ci:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test